from enum import StrEnum


class CompanyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class MembershipRole(StrEnum):
    OWNER_ADMIN = "OWNER_ADMIN"
    SUPERVISOR = "SUPERVISOR"
    DRIVER = "DRIVER"


class MembershipStatus(StrEnum):
    INVITED = "INVITED"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class OtpChallengeStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CONSUMED = "CONSUMED"
    EXPIRED = "EXPIRED"
    EXHAUSTED = "EXHAUSTED"
    CANCELLED = "CANCELLED"


class SiteStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class FleetAssetType(StrEnum):
    TIPPER = "TIPPER"
    EXCAVATOR = "EXCAVATOR"
    BACKHOE_LOADER = "BACKHOE_LOADER"
    ROLLER = "ROLLER"
    GRADER = "GRADER"


class AssetOwnershipType(StrEnum):
    OWNED = "OWNED"
    RENTED = "RENTED"


class FleetAssetStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class DevicePlatform(StrEnum):
    ANDROID = "ANDROID"
    IOS = "IOS"
    WEB = "WEB"
    OTHER = "OTHER"


class DeviceStatus(StrEnum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"


class OperationalEventType(StrEnum):
    TRIP_COMPLETE = "TRIP_COMPLETE"
    KM_READING = "KM_READING"
    HMR_READING = "HMR_READING"
    DIESEL = "DIESEL"
    EMERGENCY = "EMERGENCY"


class VerificationStatus(StrEnum):
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DISPUTED = "DISPUTED"
    AMENDED = "AMENDED"


class KmReadingType(StrEnum):
    START_READING = "START_READING"
    END_READING = "END_READING"


class HourMeterReadingType(StrEnum):
    START_READING = "START_READING"
    END_READING = "END_READING"


class DutySessionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"


class OwnerOperationAction(StrEnum):
    """Business intents supported by the Owner relationship orchestrator."""

    ACTIVATE_PERSON = "ACTIVATE_PERSON"
    SET_SUPERVISOR_SITES = "SET_SUPERVISOR_SITES"
    DEACTIVATE_PERSON = "DEACTIVATE_PERSON"
    DEPLOY_ASSET = "DEPLOY_ASSET"
    MOVE_DEPLOYMENT = "MOVE_DEPLOYMENT"
    REMOVE_DEPLOYMENT = "REMOVE_DEPLOYMENT"
    ASSIGN_DRIVER = "ASSIGN_DRIVER"
    REASSIGN_DRIVER = "REASSIGN_DRIVER"
    END_ASSIGNMENT = "END_ASSIGNMENT"
    DEACTIVATE_ASSET = "DEACTIVATE_ASSET"
    FORCE_CLOSE_DUTY_AND_DEACTIVATE_ASSET = "FORCE_CLOSE_DUTY_AND_DEACTIVATE_ASSET"
    REACTIVATE_ASSET = "REACTIVATE_ASSET"
    DEACTIVATE_SITE = "DEACTIVATE_SITE"
    REACTIVATE_SITE = "REACTIVATE_SITE"


class EmergencyCategory(StrEnum):
    BREAKDOWN = "BREAKDOWN"
    ACCIDENT = "ACCIDENT"
    TYRE_OR_VEHICLE_PROBLEM = "TYRE_OR_VEHICLE_PROBLEM"
    CONTACT_SUPERVISOR = "CONTACT_SUPERVISOR"


class EmergencyStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class SiteClosureStatus(StrEnum):
    OPEN = "OPEN"
    READY_TO_CLOSE = "READY_TO_CLOSE"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"


class MaintenanceTaskCode(StrEnum):
    ENGINE_SERVICE = "ENGINE_SERVICE"
    ENGINE_OIL = "ENGINE_OIL"
    ENGINE_OIL_FILTER = "ENGINE_OIL_FILTER"
    AIR_FILTER_CLEAN = "AIR_FILTER_CLEAN"
    AIR_FILTER_REPLACE = "AIR_FILTER_REPLACE"
    FUEL_FILTER = "FUEL_FILTER"
    GREASING = "GREASING"
    TYRE_PRESSURE_CHECK = "TYRE_PRESSURE_CHECK"
    TYRE_INSPECTION = "TYRE_INSPECTION"
    TYRE_ROTATION = "TYRE_ROTATION"
    TYRE_REPLACEMENT = "TYRE_REPLACEMENT"
    HUB_SERVICE = "HUB_SERVICE"
    WHEEL_BEARING_INSPECTION = "WHEEL_BEARING_INSPECTION"
    BRAKE_INSPECTION = "BRAKE_INSPECTION"
    BRAKE_SERVICE = "BRAKE_SERVICE"
    TRANSMISSION_SERVICE = "TRANSMISSION_SERVICE"
    DIFFERENTIAL_OIL = "DIFFERENTIAL_OIL"
    HYDRAULIC_OIL = "HYDRAULIC_OIL"
    HYDRAULIC_FILTER = "HYDRAULIC_FILTER"
    HYDRAULIC_HOSE_INSPECTION = "HYDRAULIC_HOSE_INSPECTION"
    COOLANT = "COOLANT"
    BATTERY_INSPECTION = "BATTERY_INSPECTION"
    BELT_HOSE_INSPECTION = "BELT_HOSE_INSPECTION"
    UNDERCARRIAGE_INSPECTION = "UNDERCARRIAGE_INSPECTION"
    TRACK_TENSION_CHECK = "TRACK_TENSION_CHECK"
    SWING_BEARING_GREASING = "SWING_BEARING_GREASING"
    GENERAL_INSPECTION = "GENERAL_INSPECTION"
    CUSTOM = "CUSTOM"


class MaintenanceActionType(StrEnum):
    INSPECT = "INSPECT"
    CLEAN = "CLEAN"
    LUBRICATE = "LUBRICATE"
    SERVICE = "SERVICE"
    REPLACE = "REPLACE"


class MaintenanceCriterionBasis(StrEnum):
    CALENDAR_DAYS = "CALENDAR_DAYS"
    ODOMETER_KM = "ODOMETER_KM"
    HOUR_METER_HOURS = "HOUR_METER_HOURS"


class MaintenanceDueState(StrEnum):
    NOT_DUE = "NOT_DUE"
    DUE_SOON = "DUE_SOON"
    DUE = "DUE"
    OVERDUE = "OVERDUE"
    UNKNOWN = "UNKNOWN"


class MaintenancePlanSource(StrEnum):
    CUSTOM = "CUSTOM"
    SUGGESTED_TEMPLATE = "SUGGESTED_TEMPLATE"
    COPIED_ASSET = "COPIED_ASSET"
    COMPANY_DEFAULT = "COMPANY_DEFAULT"


class MaintenanceWorkOrderStatus(StrEnum):
    DRAFT = "DRAFT"
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class MaintenanceTemplateSourceType(StrEnum):
    COMPANY_DEFAULT = "COMPANY_DEFAULT"
    OEM = "OEM"
    OTHER = "OTHER"


class MaintenanceTemplateVerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
