"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { AssetOwnershipType, AssetSiteDeployment, DriverAssetAssignment, DriverCandidate, FleetAssetType, MembershipRole, OwnerAsset, OwnerPerson, OwnerSite } from "../../lib/types";
import { Badge, Metric, Select } from "../shared/Ui";
import { assetCapabilities, assetTypes, title } from "./catalogs";

type WebRequest = <T>(path: string, options?: RequestInit) => Promise<T>;
type Common = { apiRequest: WebRequest; reload: () => Promise<void>; setError: (message: string) => void };

async function act(setError: Common["setError"], reload: Common["reload"], action: () => Promise<unknown>) {
  setError("");
  try { await action(); await reload(); }
  catch (caught) { setError(caught instanceof Error ? caught.message : "The request failed."); }
}

function assetLabel(asset: OwnerAsset) { return asset.registration_number || asset.short_name || asset.asset_code; }

export function FleetOverview({ assets }: { assets: OwnerAsset[] }) {
  const active = assets.filter((asset) => asset.status === "ACTIVE");
  const tippers = active.filter((asset) => asset.asset_type === "TIPPER").length;
  return <section aria-labelledby="fleet-overview-title"><h2 id="fleet-overview-title">Fleet overview</h2><div className="metric-grid fleet-metrics">
    <Metric label="Active assets" value={active.length} /><Metric label="Tippers" value={tippers} /><Metric label="Machinery" value={active.length - tippers} />
    <Metric label="Owned" value={active.filter((asset) => asset.ownership_type === "OWNED").length} /><Metric label="Rented" value={active.filter((asset) => asset.ownership_type === "RENTED").length} />
    <Metric label="Assigned" value={active.filter((asset) => asset.has_active_assignment).length} /><Metric label="Unassigned" value={active.filter((asset) => !asset.has_active_assignment).length} />
    <Metric label="Deployed" value={active.filter((asset) => asset.current_deployment).length} /><Metric label="Undeployed" value={active.filter((asset) => !asset.current_deployment).length} />
  </div></section>;
}

export function PeoplePanel({ people, apiRequest, reload, setError }: Common & { people: OwnerPerson[] }) {
  const [query, setQuery] = useState(""); const [phone, setPhone] = useState(""); const [name, setName] = useState("");
  const [role, setRole] = useState<"DRIVER" | "SUPERVISOR">("DRIVER"); const [editing, setEditing] = useState<OwnerPerson | null>(null);
  const shown = people.filter((person) => person.role !== "OWNER_ADMIN" && `${person.display_name} ${person.phone} ${person.role}`.toLowerCase().includes(query.toLowerCase()));
  const submit = (event: FormEvent) => { event.preventDefault(); void act(setError, reload, async () => { await apiRequest("/api/v1/owner/people/invite", { method: "POST", body: JSON.stringify({ phone, display_name: name, role }) }); setPhone(""); setName(""); }); };
  return <section><div className="section-heading"><div><h2>People</h2><p className="muted">Invite Drivers and Supervisors, then manage their lifecycle without deleting history.</p></div><input aria-label="Search people" placeholder="Search people" value={query} onChange={(event) => setQuery(event.target.value)} /></div>
    <form className="inline-form" onSubmit={submit}><input aria-label="Person phone" placeholder="Phone in E.164" value={phone} onChange={(event) => setPhone(event.target.value)} required /><input aria-label="Display name" placeholder="Display name" value={name} onChange={(event) => setName(event.target.value)} required /><select aria-label="Role" value={role} onChange={(event) => setRole(event.target.value as typeof role)}><option value="DRIVER">Driver / Operator</option><option value="SUPERVISOR">Supervisor</option></select><button type="submit">Invite person</button></form>
    <div className="table-card">{shown.length === 0 && <p className="empty-state">No people match this search.</p>}{shown.map((person) => editing?.membership_id === person.membership_id ? <form className="table-row" key={person.membership_id} onSubmit={(event) => { event.preventDefault(); void act(setError, reload, async () => { await apiRequest(`/api/v1/owner/people/${person.membership_id}`, { method: "PATCH", body: JSON.stringify({ display_name: editing.display_name, role: editing.role }) }); setEditing(null); }); }}><input aria-label="Edit display name" value={editing.display_name} onChange={(event) => setEditing({ ...editing, display_name: event.target.value })} /><select aria-label="Edit role" value={editing.role} onChange={(event) => setEditing({ ...editing, role: event.target.value as MembershipRole })}><option value="DRIVER">Driver / Operator</option><option value="SUPERVISOR">Supervisor</option></select><button type="submit">Save</button><button className="secondary" type="button" onClick={() => setEditing(null)}>Cancel</button></form> : <div className="table-row" key={person.membership_id}><div><strong>{person.display_name}</strong><small>{person.phone}</small></div><span>{title(person.role)}</span><span className={`badge ${person.status === "ACTIVE" ? "active" : ""}`}>{person.status}</span><span>{person.current_asset_code ? `${person.current_asset_code} · ${person.current_site_name}` : person.sites.map((site) => site.site_name).join(", ") || "No current allocation"}</span><div className="row-actions"><button className="secondary" type="button" onClick={() => setEditing(person)}>Edit</button><button className="secondary" type="button" onClick={() => void act(setError, reload, () => apiRequest(`/api/v1/owner/people/${person.membership_id}/${person.status === "INACTIVE" ? "reactivate" : "deactivate"}`, { method: "POST" }))}>{person.status === "INACTIVE" ? "Reactivate" : "Deactivate"}</button></div></div>)}</div>
  </section>;
}

export function SitesPanel({ sites, people, apiRequest, reload, setError }: Common & { sites: OwnerSite[]; people: OwnerPerson[] }) {
  const [query, setQuery] = useState(""); const [name, setName] = useState(""); const [code, setCode] = useState(""); const [location, setLocation] = useState(""); const [editing, setEditing] = useState<OwnerSite | null>(null); const [grant, setGrant] = useState<Record<string, string>>({});
  const supervisors = people.filter((person) => person.role === "SUPERVISOR" && person.status === "ACTIVE");
  const shown = sites.filter((site) => `${site.name} ${site.code ?? ""} ${site.location_description ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  return <section><div className="section-heading"><div><h2>Sites</h2><p className="muted">Maintain work sites and the Supervisors allowed to review each site.</p></div><input aria-label="Search sites" placeholder="Search sites" value={query} onChange={(event) => setQuery(event.target.value)} /></div>
    <form className="inline-form" onSubmit={(event) => { event.preventDefault(); void act(setError, reload, async () => { await apiRequest("/api/v1/owner/sites", { method: "POST", body: JSON.stringify({ name, code: code || null, location_description: location || null }) }); setName(""); setCode(""); setLocation(""); }); }}><input aria-label="Site name" placeholder="Site name" value={name} onChange={(event) => setName(event.target.value)} required /><input aria-label="Site code" placeholder="Code" value={code} onChange={(event) => setCode(event.target.value)} /><input aria-label="Site location" placeholder="Location description" value={location} onChange={(event) => setLocation(event.target.value)} /><button type="submit">Add site</button></form>
    <div className="management-grid">{shown.map((site) => <article className="management-card" key={site.id}>{editing?.id === site.id ? <form className="stack" onSubmit={(event) => { event.preventDefault(); void act(setError, reload, async () => { await apiRequest(`/api/v1/owner/sites/${site.id}`, { method: "PATCH", body: JSON.stringify({ name: editing.name, code: editing.code || null, location_description: editing.location_description || null }) }); setEditing(null); }); }}><input aria-label="Edit site name" value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })} /><input aria-label="Edit site code" value={editing.code ?? ""} onChange={(event) => setEditing({ ...editing, code: event.target.value || null })} /><input aria-label="Edit location" value={editing.location_description ?? ""} onChange={(event) => setEditing({ ...editing, location_description: event.target.value || null })} /><div className="row-actions"><button type="submit">Save</button><button className="secondary" type="button" onClick={() => setEditing(null)}>Cancel</button></div></form> : <><div className="card-title"><div><h3>{site.name}</h3><p className="muted">{site.code || "No code"} · {site.location_description || "No location"}</p></div><Badge status={site.status} /></div><p>{site.asset_count} deployed asset{site.asset_count === 1 ? "" : "s"}</p><div className="chip-list">{site.supervisors.map((supervisor) => <span className="chip" key={supervisor.membership_id}>{supervisor.display_name}<button aria-label={`Revoke ${supervisor.display_name} from ${site.name}`} type="button" onClick={() => void act(setError, reload, () => apiRequest(`/api/v1/owner/sites/${site.id}/supervisors/${supervisor.membership_id}`, { method: "DELETE" }))}>×</button></span>)}</div><div className="row-actions"><button className="secondary" type="button" onClick={() => setEditing(site)}>Edit</button><button className="secondary" type="button" onClick={() => void act(setError, reload, () => apiRequest(`/api/v1/owner/sites/${site.id}/${site.status === "ACTIVE" ? "deactivate" : "reactivate"}`, { method: "POST" }))}>{site.status === "ACTIVE" ? "Deactivate" : "Reactivate"}</button></div></>}
      {site.status === "ACTIVE" && <form className="inline-form compact" onSubmit={(event) => { event.preventDefault(); const supervisor = grant[site.id]; if (!supervisor) return; void act(setError, reload, () => apiRequest(`/api/v1/owner/sites/${site.id}/supervisors`, { method: "POST", body: JSON.stringify({ supervisor_membership_id: supervisor }) })); }}><select aria-label={`Supervisor for ${site.name}`} value={grant[site.id] ?? ""} onChange={(event) => setGrant({ ...grant, [site.id]: event.target.value })} required><option value="">Choose Supervisor…</option>{supervisors.filter((person) => !site.supervisors.some((item) => item.membership_id === person.membership_id)).map((person) => <option key={person.membership_id} value={person.membership_id}>{person.display_name}</option>)}</select><button type="submit">Grant access</button></form>}</article>)}</div>
  </section>;
}

type AssetDraft = { asset_type: FleetAssetType; ownership_type: AssetOwnershipType; asset_code: string; registration_number: string; short_name: string; manufacturer: string; model: string; rental_party_name: string; rental_start_date: string; rental_end_date: string };
const blankAsset: AssetDraft = { asset_type: "TIPPER", ownership_type: "OWNED", asset_code: "", registration_number: "", short_name: "", manufacturer: "", model: "", rental_party_name: "", rental_start_date: "", rental_end_date: "" };

function AssetFields({ draft, setDraft, editing = false }: { draft: AssetDraft; setDraft: (draft: AssetDraft) => void; editing?: boolean }) {
  const machinery = draft.asset_type !== "TIPPER";
  return <><label>Asset type<select disabled={editing} value={draft.asset_type} onChange={(event) => setDraft({ ...draft, asset_type: event.target.value as FleetAssetType })}>{assetTypes.map((type) => <option key={type} value={type}>{title(type)}</option>)}</select></label><label>Ownership<select value={draft.ownership_type} onChange={(event) => setDraft({ ...draft, ownership_type: event.target.value as AssetOwnershipType })}><option value="OWNED">Owned</option><option value="RENTED">Rented</option></select></label><label>Asset code<input value={draft.asset_code} onChange={(event) => setDraft({ ...draft, asset_code: event.target.value })} required /></label>{!machinery && <label>Registration<input value={draft.registration_number} onChange={(event) => setDraft({ ...draft, registration_number: event.target.value })} required /></label>}<label>Short name<input value={draft.short_name} onChange={(event) => setDraft({ ...draft, short_name: event.target.value })} required={machinery} /></label><label>Manufacturer<input value={draft.manufacturer} onChange={(event) => setDraft({ ...draft, manufacturer: event.target.value })} /></label><label>Model<input value={draft.model} onChange={(event) => setDraft({ ...draft, model: event.target.value })} /></label>{draft.ownership_type === "RENTED" && <><label>Rental party<input value={draft.rental_party_name} onChange={(event) => setDraft({ ...draft, rental_party_name: event.target.value })} required /></label><label>Rental start<input type="date" value={draft.rental_start_date} onChange={(event) => setDraft({ ...draft, rental_start_date: event.target.value })} /></label><label>Rental end<input type="date" value={draft.rental_end_date} onChange={(event) => setDraft({ ...draft, rental_end_date: event.target.value })} /></label></>}</>;
}

function assetPayload(draft: AssetDraft, includeType: boolean) {
  return { ...(includeType ? { asset_type: draft.asset_type } : {}), ownership_type: draft.ownership_type, asset_code: draft.asset_code, registration_number: draft.registration_number || null, short_name: draft.short_name || null, manufacturer: draft.manufacturer || null, model: draft.model || null, rental_party_name: draft.ownership_type === "RENTED" ? draft.rental_party_name || null : null, rental_start_date: draft.ownership_type === "RENTED" ? draft.rental_start_date || null : null, rental_end_date: draft.ownership_type === "RENTED" ? draft.rental_end_date || null : null };
}

export function FleetPanel({ assets, apiRequest, reload, setError }: Common & { assets: OwnerAsset[] }) {
  const [draft, setDraft] = useState<AssetDraft>(blankAsset); const [editingId, setEditingId] = useState(""); const [query, setQuery] = useState(""); const [typeFilter, setTypeFilter] = useState(""); const [ownershipFilter, setOwnershipFilter] = useState(""); const [statusFilter, setStatusFilter] = useState("");
  const shown = assets.filter((asset) => (!query || `${asset.asset_code} ${asset.registration_number ?? ""} ${asset.short_name ?? ""}`.toLowerCase().includes(query.toLowerCase())) && (!typeFilter || asset.asset_type === typeFilter) && (!ownershipFilter || asset.ownership_type === ownershipFilter) && (!statusFilter || asset.status === statusFilter));
  const edit = (asset: OwnerAsset) => { setEditingId(asset.id); setDraft({ asset_type: asset.asset_type, ownership_type: asset.ownership_type, asset_code: asset.asset_code, registration_number: asset.registration_number ?? "", short_name: asset.short_name ?? "", manufacturer: asset.manufacturer ?? "", model: asset.model ?? "", rental_party_name: asset.rental_party_name ?? "", rental_start_date: asset.rental_start_date ?? "", rental_end_date: asset.rental_end_date ?? "" }); };
  return <section><h2>Fleet</h2><p className="muted">Manage Tippers and heavy machinery across owned and rented fleets.</p><form className="form-grid asset-form" onSubmit={(event) => { event.preventDefault(); const endpoint = editingId ? `/api/v1/owner/assets/${editingId}` : "/api/v1/owner/assets"; void act(setError, reload, async () => { await apiRequest(endpoint, { method: editingId ? "PATCH" : "POST", body: JSON.stringify(assetPayload(draft, !editingId)) }); setEditingId(""); setDraft(blankAsset); }); }}><AssetFields draft={draft} setDraft={setDraft} editing={Boolean(editingId)} /><div className="row-actions"><button type="submit">{editingId ? "Save asset" : "Add asset"}</button>{editingId && <button className="secondary" type="button" onClick={() => { setEditingId(""); setDraft(blankAsset); }}>Cancel</button>}</div></form>
    <div className="filter-bar"><input aria-label="Search fleet" placeholder="Search fleet" value={query} onChange={(event) => setQuery(event.target.value)} /><select aria-label="Filter asset type" value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)}><option value="">All asset types</option>{assetTypes.map((type) => <option value={type} key={type}>{title(type)}</option>)}</select><select aria-label="Filter ownership" value={ownershipFilter} onChange={(event) => setOwnershipFilter(event.target.value)}><option value="">Owned and rented</option><option value="OWNED">Owned</option><option value="RENTED">Rented</option></select><select aria-label="Filter status" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div>
    <div className="management-grid">{shown.map((asset) => { const capability = assetCapabilities[asset.asset_type]; return <article className="management-card" key={asset.id}><div className="card-title"><div><h3>{assetLabel(asset)}</h3><p className="muted">{asset.asset_code}</p></div><Badge status={asset.status} /></div><p><strong>{title(asset.asset_type)}</strong> · {title(asset.ownership_type)}</p><p>{[asset.manufacturer, asset.model].filter(Boolean).join(" ") || "Manufacturer/model not set"}</p>{asset.ownership_type === "RENTED" && <p>Rented from {asset.rental_party_name || "unspecified party"}</p>}<div className="chip-list">{capability.trips && <span className="chip">Trips</span>}{capability.odometer && <span className="chip">Odometer</span>}{capability.hourMeter && <span className="chip">HMR</span>}<span className="chip">Diesel</span><span className="chip">Duty</span></div><p className="muted">{asset.current_deployment ? `At ${asset.current_deployment.site_name}` : "Undeployed"} · {asset.active_assignment ? `Assigned to ${asset.active_assignment.driver_name}` : "Unassigned"}</p><div className="row-actions"><button className="secondary" type="button" onClick={() => edit(asset)}>Edit</button><button className="secondary" type="button" onClick={() => void act(setError, reload, () => apiRequest(`/api/v1/owner/assets/${asset.id}/${asset.status === "ACTIVE" ? "deactivate" : "reactivate"}`, { method: "POST" }))}>{asset.status === "ACTIVE" ? "Deactivate" : "Reactivate"}</button></div></article>; })}</div>
  </section>;
}

export function DeploymentsPanel({ assets, sites, apiRequest, reload, setError }: Common & { assets: OwnerAsset[]; sites: OwnerSite[] }) {
  const selectable = assets.filter((asset) => asset.status === "ACTIVE"); const activeSites = sites.filter((site) => site.status === "ACTIVE"); const [assetId, setAssetId] = useState(""); const [siteId, setSiteId] = useState(""); const [history, setHistory] = useState<AssetSiteDeployment[]>([]); const selected = assets.find((asset) => asset.id === assetId);
  useEffect(() => { if (!assetId) return; void apiRequest<AssetSiteDeployment[]>(`/api/v1/owner/assets/${assetId}/deployments`).then(setHistory).catch((caught) => setError(caught instanceof Error ? caught.message : "Could not load deployment history.")); }, [apiRequest, assetId, setError]);
  return <section><h2>Deployments</h2><p className="muted">Deploy an asset before assigning a Driver / Operator. Moving an actively assigned asset is blocked by the server.</p><form className="form-grid" onSubmit={(event) => { event.preventDefault(); void act(setError, reload, () => apiRequest(`/api/v1/owner/assets/${assetId}/deployment`, { method: "POST", body: JSON.stringify({ site_id: siteId }) })); }}><Select label="Asset" value={assetId} onChange={(value) => { setAssetId(value); setHistory([]); }} options={selectable.map((asset) => [asset.id, `${assetLabel(asset)} · ${title(asset.asset_type)}`])} /><Select label="Site" value={siteId} onChange={setSiteId} options={activeSites.map((site) => [site.id, site.name])} /><button type="submit">{selected?.current_deployment ? "Move asset" : "Deploy asset"}</button></form>{selected && <article className="management-card"><h3>Current deployment</h3><p>{selected.current_deployment ? `${assetLabel(selected)} is at ${selected.current_deployment.site_name}.` : `${assetLabel(selected)} is undeployed.`}</p>{selected.current_deployment && <button className="secondary" type="button" onClick={() => void act(setError, reload, () => apiRequest(`/api/v1/owner/assets/${assetId}/deployment`, { method: "DELETE" }))}>Remove deployment</button>}<h3>History</h3><div className="table-card">{history.length === 0 && <p className="empty-state">No deployment history.</p>}{history.map((item) => <div className="table-row" key={item.id}><strong>{item.site_name}</strong><span>{new Date(item.starts_at).toLocaleString()}</span><span>{item.ends_at ? `Ended ${new Date(item.ends_at).toLocaleString()}` : "Current"}</span></div>)}</div></article>}</section>;
}

export function AssignmentsPanel({ assets, apiRequest, reload, setError }: Common & { assets: OwnerAsset[] }) {
  const selectable = assets.filter((asset) => asset.status === "ACTIVE" && asset.current_deployment); const [assetId, setAssetId] = useState(""); const [driverId, setDriverId] = useState(""); const [minutes, setMinutes] = useState("600"); const [eligible, setEligible] = useState<DriverCandidate[]>([]); const [history, setHistory] = useState<DriverAssetAssignment[]>([]); const selected = assets.find((asset) => asset.id === assetId);
  useEffect(() => { if (!assetId) return; Promise.all([apiRequest<DriverCandidate[]>(`/api/v1/owner/assets/${assetId}/eligible-drivers`), apiRequest<DriverAssetAssignment[]>(`/api/v1/owner/assets/${assetId}/assignments`)]).then(([drivers, items]) => { setEligible(drivers); setHistory(items); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Could not load assignment options.")); }, [apiRequest, assetId, setError]);
  const candidates = useMemo(() => selected?.active_assignment ? [{ membership_id: selected.active_assignment.driver_membership_id, display_name: selected.active_assignment.driver_name }, ...eligible.filter((item) => item.membership_id !== selected.active_assignment?.driver_membership_id)] : eligible, [eligible, selected]);
  return <section><h2>Driver / Operator assignments</h2><p className="muted">Assign any deployed Tipper or machine. Regular duty is snapshotted when duty begins.</p><form className="form-grid" onSubmit={(event) => { event.preventDefault(); const suffix = selected?.has_active_assignment ? "/assignment/reassign" : "/assignment"; void act(setError, reload, () => apiRequest(`/api/v1/owner/assets/${assetId}${suffix}`, { method: "POST", body: JSON.stringify({ driver_membership_id: driverId, regular_duty_minutes: Number(minutes) }) })); }}><Select label="Deployed asset" value={assetId} onChange={(value) => { setAssetId(value); setDriverId(""); setEligible([]); setHistory([]); }} options={selectable.map((asset) => [asset.id, `${assetLabel(asset)} · ${asset.current_deployment?.site_name}`])} /><Select label="Driver / Operator" value={driverId} onChange={setDriverId} options={candidates.map((person) => [person.membership_id, person.display_name])} /><label>Regular duty<select value={minutes} onChange={(event) => setMinutes(event.target.value)}><option value="480">8 hours</option><option value="600">10 hours</option><option value="720">12 hours</option></select></label><button type="submit">{selected?.has_active_assignment ? "Reassign" : "Assign"}</button></form>{selected && <article className="management-card"><h3>Current assignment</h3><p>{selected.active_assignment ? `${selected.active_assignment.driver_name} operates ${assetLabel(selected)} at ${selected.active_assignment.site_name}.` : `${assetLabel(selected)} is unassigned.`}</p>{selected.active_assignment && <button className="secondary" type="button" onClick={() => void act(setError, reload, () => apiRequest(`/api/v1/owner/assets/${assetId}/assignment`, { method: "DELETE" }))}>Unassign</button>}<h3>History</h3><div className="table-card">{history.length === 0 && <p className="empty-state">No assignment history.</p>}{history.map((item) => <div className="table-row" key={item.assignment_id}><strong>{item.driver_name}</strong><span>{item.site_name}</span><span>{item.regular_duty_minutes / 60}h duty</span><span>{item.ends_at ? "Closed" : "Current"}</span></div>)}</div></article>}</section>;
}
