"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import type { ReportTemplate } from "../../lib/types";
import { machineryColumns, managementColumns, sheetCatalog, tipperColumns, title } from "./catalogs";

type WebRequest = <T>(path: string, options?: RequestInit) => Promise<T>;
type Draft = Pick<ReportTemplate, "name" | "included_sheets" | "management_dashboard_columns" | "tipper_daily_columns" | "machinery_daily_columns">;
const blank: Draft = { name: "", included_sheets: ["management_dashboard", "tipper_daily", "machinery_daily", "exceptions"], management_dashboard_columns: [...managementColumns], tipper_daily_columns: [...tipperColumns], machinery_daily_columns: [...machineryColumns] };

function Checklist({ legend, values, selected, onChange }: { legend: string; values: readonly string[]; selected: string[]; onChange: (next: string[]) => void }) {
  return <fieldset><legend>{legend}</legend><div className="checkbox-grid">{values.map((value) => { const mandatory = value === "asset"; return <label className="check-option" key={value}><input type="checkbox" checked={mandatory || selected.includes(value)} disabled={mandatory} onChange={(event) => onChange(event.target.checked ? [...selected, value] : selected.filter((item) => item !== value))} />{title(value)}</label>; })}</div></fieldset>;
}

export function ReportTemplates({ apiRequest, setError }: { apiRequest: WebRequest; setError: (message: string) => void }) {
  const [templates, setTemplates] = useState<ReportTemplate[]>([]); const [selectedId, setSelectedId] = useState(""); const [editingId, setEditingId] = useState(""); const [draft, setDraft] = useState<Draft>(blank); const [duplicateName, setDuplicateName] = useState("");
  const load = useCallback(async () => { try { const items = await apiRequest<ReportTemplate[]>("/api/v1/owner/report-templates"); setTemplates(items); setSelectedId((value) => value || items.find((item) => item.is_default)?.id || items[0]?.id || ""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load report templates."); } }, [apiRequest, setError]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const selected = templates.find((item) => item.id === selectedId);
  const run = async (action: () => Promise<unknown>) => { setError(""); try { await action(); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "The template request failed."); } };
  const beginEdit = (item: ReportTemplate) => { setEditingId(item.id); setDraft({ name: item.name, included_sheets: [...item.included_sheets], management_dashboard_columns: [...item.management_dashboard_columns], tipper_daily_columns: [...item.tipper_daily_columns], machinery_daily_columns: [...item.machinery_daily_columns] }); };
  const submit = (event: FormEvent) => { event.preventDefault(); void run(async () => { await apiRequest(editingId ? `/api/v1/owner/report-templates/${editingId}` : "/api/v1/owner/report-templates", { method: editingId ? "PATCH" : "POST", body: JSON.stringify(draft) }); setEditingId(""); setDraft(blank); }); };
  return <section><h2>Report templates</h2><p className="muted">Choose the sheets and columns included in Owner Excel exports. Asset remains the mandatory first column.</p><div className="template-layout"><div className="table-card">{templates.map((item) => <button className={`table-row ${selectedId === item.id ? "selected-row" : ""}`} type="button" key={item.id} onClick={() => setSelectedId(item.id)}><strong>{item.name}</strong><span>{item.is_builtin ? "Built-in" : "Custom"}</span><span>{item.included_sheets.length} sheets</span><span>{item.is_default ? "Default" : ""}</span></button>)}</div>{selected && <article className="management-card"><div className="card-title"><div><h3>{selected.name}</h3><p className="muted">{selected.included_sheets.map(title).join(", ")}</p></div>{selected.is_default && <span className="badge active">DEFAULT</span>}</div><div className="row-actions">{!selected.is_default && <button type="button" onClick={() => void run(() => apiRequest(`/api/v1/owner/report-templates/${selected.id}/default`, { method: "POST" }))}>Set as default</button>}{!selected.is_builtin && <button className="secondary" type="button" onClick={() => beginEdit(selected)}>Edit</button>}{!selected.is_builtin && <button className="secondary" type="button" onClick={() => void run(() => apiRequest(`/api/v1/owner/report-templates/${selected.id}`, { method: "DELETE" }))}>Delete</button>}</div><form className="inline-form compact" onSubmit={(event) => { event.preventDefault(); if (!duplicateName) return; void run(async () => { const copy = await apiRequest<ReportTemplate>(`/api/v1/owner/report-templates/${selected.id}/duplicate`, { method: "POST", body: JSON.stringify({ name: duplicateName }) }); setSelectedId(copy.id); setDuplicateName(""); }); }}><input aria-label="Duplicate template name" placeholder="New copy name" value={duplicateName} onChange={(event) => setDuplicateName(event.target.value)} required /><button type="submit">Duplicate</button></form></article>}</div>
    <form className="template-editor" onSubmit={submit}><h3>{editingId ? "Edit custom template" : "Create custom template"}</h3><label>Template name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} required /></label><Checklist legend="Workbook sheets" values={sheetCatalog.map(([id]) => id)} selected={draft.included_sheets} onChange={(included_sheets) => setDraft({ ...draft, included_sheets })} /><Checklist legend="Management dashboard columns" values={managementColumns} selected={draft.management_dashboard_columns} onChange={(management_dashboard_columns) => setDraft({ ...draft, management_dashboard_columns })} /><Checklist legend="Tipper daily columns" values={tipperColumns} selected={draft.tipper_daily_columns} onChange={(tipper_daily_columns) => setDraft({ ...draft, tipper_daily_columns })} /><Checklist legend="Machinery daily columns" values={machineryColumns} selected={draft.machinery_daily_columns} onChange={(machinery_daily_columns) => setDraft({ ...draft, machinery_daily_columns })} /><div className="row-actions"><button type="submit">{editingId ? "Save template" : "Create template"}</button>{editingId && <button className="secondary" type="button" onClick={() => { setEditingId(""); setDraft(blank); }}>Cancel</button>}</div></form>
  </section>;
}
